<a href="https://colab.research.google.com/github/vineelagurram2002/Neural-Networks/blob/main/Vineela_Gurram_700757960_.ICP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
class Employee:
    # Class variable to count the number of Employees
    employee_count = 0
    total_salary = 0

    def __init__(self, name, family, salary, department):
        # Instance variables
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

        # Update the class variables
        Employee.employee_count += 1
        Employee.total_salary += salary

    # Function to calculate the average salary of all employees
    @classmethod
    def average_salary(cls):
        if cls.employee_count == 0:
            return 0
        return cls.total_salary / cls.employee_count

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        # Initialize the FulltimeEmployee instance using the parent class constructor
        super().__init__(name, family, salary, department)


# Creating instances of Employee and FulltimeEmployee
emp1 = Employee("John Doe", "Doe Family", 50000, "HR")
emp2 = FulltimeEmployee("Jane Smith", "Smith Family", 60000, "Finance")
emp3 = FulltimeEmployee("Emily Davis", "Davis Family", 55000, "IT")

# Printing the number of employees
print(f"Total number of employees: {Employee.employee_count}")

# Calculating and printing the average salary of employees
print(f"Average salary of employees: ${Employee.average_salary():.2f}")

# Accessing individual employee details
print(f"Employee 1: {emp1.name}, {emp1.family}, {emp1.salary}, {emp1.department}")
print(f"Employee 2: {emp2.name}, {emp2.family}, {emp2.salary}, {emp2.department}")
print(f"Employee 3: {emp3.name}, {emp3.family}, {emp3.salary}, {emp3.department}")


Total number of employees: 3
Average salary of employees: $55000.00
Employee 1: John Doe, Doe Family, 50000, HR
Employee 2: Jane Smith, Smith Family, 60000, Finance
Employee 3: Emily Davis, Davis Family, 55000, IT


In [2]:
import numpy as np

# Step 1: Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

# Step 2: Reshape the vector to a 4x5 array
reshaped_array = random_vector.reshape(4, 5)

# Step 3: Replace the maximum value in each row by 0
# The np.argmax function is used to find the index of the maximum element along the specified axis.
reshaped_array[np.arange(reshaped_array.shape[0]), reshaped_array.argmax(axis=1)] = 0

# Output the final array
print("Original reshaped array:\n", random_vector.reshape(4, 5))
print("\nArray after replacing the max in each row with 0:\n", reshaped_array)


Original reshaped array:
 [[ 9.74876818  0.         14.85365994  4.31549366  3.61596561]
 [ 9.84110371  0.          8.07990008  4.56931492  1.67720932]
 [13.77560967 10.12131026 12.44180072 11.0641505   0.        ]
 [14.42296042  0.          5.68872114  9.3422319   4.74066403]]

Array after replacing the max in each row with 0:
 [[ 9.74876818  0.         14.85365994  4.31549366  3.61596561]
 [ 9.84110371  0.          8.07990008  4.56931492  1.67720932]
 [13.77560967 10.12131026 12.44180072 11.0641505   0.        ]
 [14.42296042  0.          5.68872114  9.3422319   4.74066403]]
